# Generated by Django 5.1.5 on 2025-02-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRSCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('krs_number', models.CharField(max_length=10, unique=True)),
                ('nip', models.CharField(blank=True, max_length=15, null=True)),
                ('regon', models.CharField(blank=True, max_length=14, null=True)),
                ('legal_form', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
