# Generated by Django 5.1.5 on 2025-02-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_krscompany_delete_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krscompany',
            name='address',
        ),
        migrations.AddField(
            model_name='krscompany',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='krscompany',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='krscompany',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
