# Generated by Django 5.1.5 on 2025-01-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Moviedata',
        ),
    ]
