# Generated by Django 5.1.5 on 2025-01-29 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://media.licdn.com/dms/image/v2/C5122AQGeHzVmmEvW5Q/feedshare-shrink_800/feedshare-shrink_800/0/1573460295130?e=2147483647&v=beta&t=4aXjSfZb5RmDnXMAjN0Pe3I8t3A45lD-MQFp4jUKng8', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
